export const deliveries = [
  {
    id: "1",
    trackingNumber: "BZ123456",
    packageType: "Standard Parcel",
    weight: "2.5 lbs",
    dimensions: "12 x 8 x 6 inches",
    from: "123 Main St, New York, NY 10001",
    to: "456 Oak St, Los Angeles, CA 90001",
    date: "2023-03-15",
    status: "Delivered",
    updates: [
      {
        status: "Order Placed",
        date: "March 12, 2023",
        time: "10:30 AM",
        description: "Your order has been placed and is being processed.",
      },
      {
        status: "Pickup Scheduled",
        date: "March 13, 2023",
        time: "09:15 AM",
        description: "Pickup has been scheduled for your package.",
      },
      {
        status: "Package Picked Up",
        date: "March 13, 2023",
        time: "02:45 PM",
        description: "Your package has been picked up by our courier.",
      },
      {
        status: "In Transit",
        date: "March 14, 2023",
        time: "08:20 AM",
        description: "Your package is in transit to the destination.",
      },
      {
        status: "Out for Delivery",
        date: "March 15, 2023",
        time: "09:30 AM",
        description: "Your package is out for delivery.",
      },
      {
        status: "Delivered",
        date: "March 15, 2023",
        time: "02:15 PM",
        description: "Your package has been delivered successfully.",
      },
    ],
  },
  {
    id: "2",
    trackingNumber: "BZ234567",
    packageType: "Express Document",
    weight: "0.5 lbs",
    dimensions: "9 x 12 x 0.5 inches",
    from: "789 Pine St, Chicago, IL 60601",
    to: "321 Elm St, Houston, TX 77001",
    date: "2023-03-18",
    status: "In-Transit",
    updates: [
      {
        status: "Order Placed",
        date: "March 16, 2023",
        time: "11:45 AM",
        description: "Your order has been placed and is being processed.",
      },
      {
        status: "Pickup Scheduled",
        date: "March 17, 2023",
        time: "10:30 AM",
        description: "Pickup has been scheduled for your package.",
      },
      {
        status: "Package Picked Up",
        date: "March 17, 2023",
        time: "03:15 PM",
        description: "Your package has been picked up by our courier.",
      },
      {
        status: "In Transit",
        date: "March 18, 2023",
        time: "09:45 AM",
        description: "Your package is in transit to the destination.",
      },
    ],
  },
  {
    id: "3",
    trackingNumber: "BZ345678",
    packageType: "Large Parcel",
    weight: "15.2 lbs",
    dimensions: "24 x 18 x 12 inches",
    from: "555 Maple Ave, Seattle, WA 98101",
    to: "777 Cedar Rd, Miami, FL 33101",
    date: "2023-03-20",
    status: "Pending",
    updates: [
      {
        status: "Order Placed",
        date: "March 19, 2023",
        time: "02:30 PM",
        description: "Your order has been placed and is being processed.",
      },
      {
        status: "Pickup Scheduled",
        date: "March 20, 2023",
        time: "09:00 AM",
        description: "Pickup has been scheduled for your package.",
      },
    ],
  },
  {
    id: "4",
    trackingNumber: "BZ456789",
    packageType: "Fragile Parcel",
    weight: "3.7 lbs",
    dimensions: "14 x 10 x 8 inches",
    from: "222 Birch St, Boston, MA 02101",
    to: "444 Willow Dr, San Francisco, CA 94101",
    date: "2023-03-16",
    status: "Delivered",
    updates: [
      {
        status: "Order Placed",
        date: "March 13, 2023",
        time: "01:15 PM",
        description: "Your order has been placed and is being processed.",
      },
      {
        status: "Pickup Scheduled",
        date: "March 14, 2023",
        time: "10:00 AM",
        description: "Pickup has been scheduled for your package.",
      },
      {
        status: "Package Picked Up",
        date: "March 14, 2023",
        time: "03:30 PM",
        description: "Your package has been picked up by our courier.",
      },
      {
        status: "In Transit",
        date: "March 15, 2023",
        time: "08:45 AM",
        description: "Your package is in transit to the destination.",
      },
      {
        status: "Out for Delivery",
        date: "March 16, 2023",
        time: "09:15 AM",
        description: "Your package is out for delivery.",
      },
      {
        status: "Delivered",
        date: "March 16, 2023",
        time: "03:45 PM",
        description: "Your package has been delivered successfully.",
      },
    ],
  },
  {
    id: "5",
    trackingNumber: "BZ567890",
    packageType: "Heavy Parcel",
    weight: "22.8 lbs",
    dimensions: "20 x 16 x 14 inches",
    from: "888 Spruce Ln, Denver, CO 80201",
    to: "999 Aspen Ct, Phoenix, AZ 85001",
    date: "2023-03-19",
    status: "In-Transit",
    updates: [
      {
        status: "Order Placed",
        date: "March 17, 2023",
        time: "09:30 AM",
        description: "Your order has been placed and is being processed.",
      },
      {
        status: "Pickup Scheduled",
        date: "March 18, 2023",
        time: "11:15 AM",
        description: "Pickup has been scheduled for your package.",
      },
      {
        status: "Package Picked Up",
        date: "March 18, 2023",
        time: "04:00 PM",
        description: "Your package has been picked up by our courier.",
      },
      {
        status: "In Transit",
        date: "March 19, 2023",
        time: "10:30 AM",
        description: "Your package is in transit to the destination.",
      },
    ],
  },
  {
    id: "6",
    trackingNumber: "BZ678901",
    packageType: "Express Parcel",
    weight: "1.8 lbs",
    dimensions: "10 x 8 x 4 inches",
    from: "333 Oak St, Atlanta, GA 30301",
    to: "666 Pine Ave, Dallas, TX 75201",
    date: "2023-03-17",
    status: "Delivered",
    updates: [
      {
        status: "Order Placed",
        date: "March 15, 2023",
        time: "02:45 PM",
        description: "Your order has been placed and is being processed.",
      },
      {
        status: "Pickup Scheduled",
        date: "March 16, 2023",
        time: "09:30 AM",
        description: "Pickup has been scheduled for your package.",
      },
      {
        status: "Package Picked Up",
        date: "March 16, 2023",
        time: "01:15 PM",
        description: "Your package has been picked up by our courier.",
      },
      {
        status: "In Transit",
        date: "March 16, 2023",
        time: "05:30 PM",
        description: "Your package is in transit to the destination.",
      },
      {
        status: "Out for Delivery",
        date: "March 17, 2023",
        time: "08:45 AM",
        description: "Your package is out for delivery.",
      },
      {
        status: "Delivered",
        date: "March 17, 2023",
        time: "12:30 PM",
        description: "Your package has been delivered successfully.",
      },
    ],
  },
]

